name: Build and Deploy Vite/Vue App to Firebase

on:
    push:
      branches:
        - main
        - development
    pull_request:
      branches:
        - main
        - development

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'  # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Vite/Vue app
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v13.11.2
        with:
            args: deploy --only hosting
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}

